# Generated by Django 2.2.3 on 2019-07-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('comp_name', models.CharField(max_length=50)),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('sup_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
