# Generated by Django 2.2.3 on 2019-07-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='sup_code',
            field=models.CharField(blank=True, max_length=200, primary_key=True, serialize=False),
        ),
    ]
