# Generated by Django 2.2.3 on 2019-07-15 05:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POHead',
            fields=[
                ('po_no', models.IntegerField(primary_key=True, serialize=False)),
                ('po_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('appr_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PODetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.IntegerField()),
                ('amt', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item')),
                ('po_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='po.POHead')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.Supplier')),
            ],
            options={
                'unique_together': {('po_head', 'item')},
            },
        ),
    ]
