# Generated by Django 2.2.3 on 2019-07-15 08:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRHead',
            fields=[
                ('pr_no', models.AutoField(primary_key=True, serialize=False)),
                ('pr_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PRDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item')),
                ('pr_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pr.PRHead')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.Supplier')),
            ],
            options={
                'unique_together': {('pr_head', 'item')},
            },
        ),
    ]
