# Generated by Django 2.2.3 on 2019-07-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prhead',
            name='pr_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
