# Generated by Django 2.2.3 on 2019-07-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicehead',
            name='invoice_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
